title: "NIVO+ Anesthesic Digital System"
email: nivo@cares.ar
description: >-
  Plataforma para la gestión integral de documentación digital anestesiológica.
  Facilita el registro de evaluación pre anestésica, protocolo anestésico y
  post anestesia, optimizando la práctica profesional y generando documentos de
  alta calidad.
baseurl: ""
url: "https://cares.ar"
twitter_username: ""
github_username: ""
plugins:
  - jekyll-feed
include:
  - .well-known
